baseURL = "https://arcanigma.org/"
title = "Arcanigma Project"
theme = "vncnt-hugo"
language = "en"

buildDrafts = false
buildFuture = false
buildExpired = false

relativeURLs = true
disableRSS = true
enableRobotsTXT = true

[markup.goldmark.renderer]
  hardWraps = true

[params]
  author = "Arcanigma Project"
  email = "contact@arcanigma.org"
  description = "Landing Page"
  bio = """
  Free & Open Source Software
  [Copyright and Attributions](https://github.com/arcanigma/arcanigma.org/blob/master/README.md)"""
  avatar = "img/hydra-circle.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/arcanigma/"
