baseURL = "https://arcanigma.org/"
title = "Arcanigma Foundation"
theme = "vncnt-hugo"
language = "en"

buildDrafts = false
buildFuture = false
buildExpired = false

relativeURLs = true
disableRSS = true
enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = "blackfriday"

[params]
  author = "Arcanigma Foundation"
  email = "foundation@arcanigma.org"
  description = "Landing Page"
  bio = "*Free & Open Source Software*<br />[Copyright and Attributions](https://github.com/arcanigma/arcanigma.org/blob/master/README.md)"
  avatar = "img/hydra-logo.png"
  favicon = "img/favicon.ico"

  [params.contact]
    github = "https://github.com/arcanigma/"
    npm = "https://www.npmjs.com/org/arcanigma"
    slack = "https://arcanigma.slack.com"
